export type MenuItem = {
  label: string;
  children?: { label: string }[];
};

export const menu: MenuItem[] = [
  {
    label: "Motor",
    children: [
      { label: "Anel" },
      { label: "Anti Chama" },
      { label: "Atuador" },
      { label: "Bomba Oleo" },
      { label: "Bronzina" },
      { label: "Carter" },
      { label: "Comando" },
      { label: "Correia" },
      { label: "Coxim" },
      { label: "Filtro" },
      { label: "Flange" },
      { label: "Interruptor" },
      { label: "Junta" },
      { label: "Kit Distribuicao" },
      { label: "Kit Motor" },
      { label: "Pistao" },
      { label: "Retentor" },
      { label: "Rolamento" },
      { label: "Tampa" },
      { label: "Tensor" },
      { label: "Tucho" },
      { label: "Valvula" },
    ],
  },
  {
    label: "Cambio",
    children: [
      { label: "Atuador" },
      { label: "Cabo" },
      { label: "Cilindro" },
      { label: "Coifa" },
      { label: "Coxim" },
      { label: "Cruzeta" },
      { label: "Disco" },
      { label: "Filtro" },
      { label: "Homocinetica" },
      { label: "Kit Embreagem" },
      { label: "Semi Eixo" },
      { label: "Tulipa" },
    ],
  },
  {
    label: "Freios",
    children: [
      { label: "Cilindro" },
      { label: "Disco Freio" },
      { label: "Pastilha" },
      { label: "Patin Freio" },
      { label: "Sensor" },
      { label: "Servo Freio" },
      { label: "Tambor Freio" },
    ],
  },
  {
    label: "Suspensao / Direcao",
    children: [
      { label: "Amortecedor" },
      { label: "Articulacao" },
      { label: "Bandeja" },
      { label: "Barra" },
      { label: "Bieleta" },
      { label: "Braco" },
      { label: "Bucha" },
      { label: "Cubo Roda" },
      { label: "Mola" },
      { label: "Pivo" },
      { label: "Terminal" },
    ],
  },
  {
    label: "Injecao / Ignicao",
    children: [
      { label: "Bico" },
      { label: "Bobina" },
      { label: "Bomba Combustivel" },
      { label: "Cabo Ignicao" },
      { label: "Carburador" },
      { label: "Regulador" },
      { label: "Sensor" },
      { label: "Sonda Lambda" },
      { label: "Tampa" },
    ],
  },
  {
    label: "Arrefecimento",
    children: [
      { label: "Bomba Agua" },
      { label: "Mangueira" },
      { label: "Radiador" },
      { label: "Reservatorio" },
      { label: "Sensor" },
      { label: "Valvula Termostatica" },
    ],
  },
];
